### ISSUE TITLE
help decoding vendor specific attributes

### ISSUE THREAD

**Issue by ralberto** [layeh/radius#38]
Hi.  
(Sorry if this is not a right place to ask this type of question. I'm also not familiarized with radius protocol)

I'm creating an utility that will receive radius packets (via UDP socket) and decode some A/V pairs to a human readable format. With the help of this project I'm currently able to read the packages and retrieve A/V pairs using rfc2865.<attr_GetString(packet)>.

However, I really need to decode a vendor specific attribute, namely 3GPP User-Location-Info. Can someone point me in the right direction how to do that?

Thanks for any help you could provide.

**Comment by bontibon** [comment]
You'll want to use [radius-dict-gen](https://github.com/layeh/radius#radius-dictionaries) for this.  It takes in a FreeRadius dictionary file and outputs Go helper code for working with those dictionary's attributes on a packet. Once installed, you can run it like this:

```
radius-dict-gen -output generated.go -package threegpp /usr/share/freeradius/dictionary.3gpp
```

I just tried running that command on my machine, and I get errors because I have not implemented the "byte" attribute, which that dictionary apparently uses. You can either use the `-ignore` flag (e.g. `-ignore 3GPP-Session-Stop-Indicator`) if those particular attributes are of no interest to you, or open another ticket requesting that the byte attribute be supported.

**Comment by ralberto** [comment]
Thanks @bontibon.
That's really helpful. I don't need those attributes, however I think the -ignore flag is not being applied during the parse phase. So the parser fails with the error:

> ... unknown attribute type "byte`

**Comment by ralberto** [comment]
As a workaround I just commented those attributes directly on the 3gpp dictionary!
